name: application-continuous-integration

on:
  workflow_dispatch:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
        shell: bash
    environment: development
    env:
      working-directory: ./src

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
            go-version: '>=1.18.0'

      - name: Install Dependencies
        run: go mod download
        working-directory: ./src

      - name: Build Project
        run: go build ./...
        working-directory: ./src

      - name: Run Unit Tests
        run: go test ./...
        working-directory: ./src